# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        authentication\AuthBundle\Model\Users:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        maind:
            propel:
                class: authentication\AuthBundle\Model\Users
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login
                default_target_path: /players_list

            logout:
                path:   /logout
                target: /login

    access_control:
        - { path: ^/players_list, role: ROLE_USER }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
